#!/usr/bin/env bash
# shellcheck disable=SC2016  # generator: $DEST/$@ are written literally into the bundle, by design
# make-portable.sh — generate a single self-contained `agent-primer.sh`.
#
# For a brand-new machine it's handy to have ONE file you can scp / paste into a gist /
# curl. This inlines the hook script, the three policy docs, and the install + uninstall
# scripts into a single self-extracting installer. Regenerate whenever you edit
# codegraph-session-check.sh / *-policy.md / install.sh / uninstall.sh.
set -e
cd "$(dirname "$0")"
OUT="agent-primer.sh"

{
  printf '%s\n' '#!/usr/bin/env bash'
  printf '%s\n' '# agent-primer.sh — SELF-CONTAINED CodeGraph rule+hook + Karpathy + Superpowers installer.'
  printf '%s\n' '# Carry/gist/curl this ONE file to any machine. Generated by make-portable.sh — do not hand-edit.'
  printf '%s\n' '#   bash agent-primer.sh --global            # wire all your agents, every project'
  printf '%s\n' '#   bash agent-primer.sh --project [DIR]      # wire one repo'
  printf '%s\n' '#   curl -fsSL <url>/agent-primer.sh | bash -s -- --global'
  printf '%s\n' 'set -e'
  printf '%s\n' 'DEST="${AGENT_PRIMER_KIT_DIR:-$HOME/.agent-primer}"'
  printf '%s\n' 'mkdir -p "$DEST"'
  printf '%s\n' "cat > \"\$DEST/codegraph-session-check.sh\" <<'CG_EOF_SCRIPT'"
  cat codegraph-session-check.sh
  printf '%s\n' 'CG_EOF_SCRIPT'
  printf '%s\n' "cat > \"\$DEST/codegraph-policy.md\" <<'CG_EOF_POLICY'"
  cat codegraph-policy.md
  printf '%s\n' 'CG_EOF_POLICY'
  printf '%s\n' "cat > \"\$DEST/karpathy-policy.md\" <<'CG_EOF_KARPATHY'"
  cat karpathy-policy.md
  printf '%s\n' 'CG_EOF_KARPATHY'
  printf '%s\n' "cat > \"\$DEST/superpowers-policy.md\" <<'CG_EOF_SUPERPOWERS'"
  cat superpowers-policy.md
  printf '%s\n' 'CG_EOF_SUPERPOWERS'
  printf '%s\n' "cat > \"\$DEST/install.sh\" <<'CG_EOF_INSTALL'"
  cat install.sh
  printf '%s\n' 'CG_EOF_INSTALL'
  printf '%s\n' "cat > \"\$DEST/uninstall.sh\" <<'CG_EOF_UNINSTALL'"
  cat uninstall.sh
  printf '%s\n' 'CG_EOF_UNINSTALL'
  printf '%s\n' 'chmod +x "$DEST/codegraph-session-check.sh" "$DEST/install.sh" "$DEST/uninstall.sh"'
  printf '%s\n' 'echo "[agent-primer] kit extracted to $DEST"'
  printf '%s\n' 'if [ "${1:-}" = "--uninstall" ]; then shift; exec bash "$DEST/uninstall.sh" "$@"; fi'
  printf '%s\n' 'exec bash "$DEST/install.sh" "$@"'
} > "$OUT"

chmod +x "$OUT"
echo "generated $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
