#!/usr/bin/env bash
# make-portable.sh — generate a single self-contained `codegraph-bootstrap.sh`.
#
# The kit is normally 4 files. For a brand-new machine it's handy to have ONE
# file you can scp / paste into a gist / curl. This inlines the script + policy
# + installer into a single self-extracting installer. Regenerate whenever you
# edit codegraph-session-check.sh / codegraph-policy.md / install.sh.
set -e
cd "$(dirname "$0")"
OUT="codegraph-bootstrap.sh"

{
  printf '%s\n' '#!/usr/bin/env bash'
  printf '%s\n' '# codegraph-bootstrap.sh — SELF-CONTAINED CodeGraph rule+hook installer.'
  printf '%s\n' '# Carry/gist/curl this ONE file to any machine. Generated by make-portable.sh — do not hand-edit.'
  printf '%s\n' '#   bash codegraph-bootstrap.sh --global            # wire all your agents, every project'
  printf '%s\n' '#   bash codegraph-bootstrap.sh --project [DIR]      # wire one repo'
  printf '%s\n' '#   curl -fsSL <url>/codegraph-bootstrap.sh | bash -s -- --global'
  printf '%s\n' 'set -e'
  printf '%s\n' 'DEST="${CODEGRAPH_KIT_DIR:-$HOME/.codegraph-bootstrap}"'
  printf '%s\n' 'mkdir -p "$DEST"'
  printf '%s\n' "cat > \"\$DEST/codegraph-session-check.sh\" <<'CG_EOF_SCRIPT'"
  cat codegraph-session-check.sh
  printf '%s\n' 'CG_EOF_SCRIPT'
  printf '%s\n' "cat > \"\$DEST/codegraph-policy.md\" <<'CG_EOF_POLICY'"
  cat codegraph-policy.md
  printf '%s\n' 'CG_EOF_POLICY'
  printf '%s\n' "cat > \"\$DEST/install.sh\" <<'CG_EOF_INSTALL'"
  cat install.sh
  printf '%s\n' 'CG_EOF_INSTALL'
  printf '%s\n' 'chmod +x "$DEST/codegraph-session-check.sh" "$DEST/install.sh"'
  printf '%s\n' 'echo "[codegraph-bootstrap] kit extracted to $DEST"'
  printf '%s\n' 'exec bash "$DEST/install.sh" "$@"'
} > "$OUT"

chmod +x "$OUT"
echo "generated $OUT ($(wc -c < "$OUT" | tr -d ' ') bytes)"
