// Privacy gate for learning signals. Because signals persist code excerpts locally,
// this is stricter than CodeGraph's indexer: we reuse its scan-filter philosophy
// (ignore deps/build dirs, size cap, source-extension gate) AND hard-skip secret
// files, exclude generated code, scrub secrets from excerpts, and cap their size.

import { basename } from 'node:path';

export const MAX_FILE_SIZE = 1024 * 1024; // 1 MB
export const MAX_EXCERPT_BYTES = 2048;
export const MAX_EXCERPT_LINES = 40;

const IGNORE_DIRS = new Set([
  'node_modules', 'bower_components', '.yarn', '.pnpm-store',
  '.next', '.nuxt', '.svelte-kit', '.turbo', '.vite', '.parcel-cache', '.angular', '.vercel', '.netlify',
  'dist', 'build', 'out', '.output', 'coverage', '.nyc_output',
  '__pycache__', '.venv', 'venv', '.mypy_cache', '.pytest_cache', '.ruff_cache', '.tox',
  'target', '.gradle', 'obj', 'vendor', '.build', 'Pods', 'DerivedData', '.dart_tool', '.cache', '.git',
]);

// Files whose very contents are secrets — never capture, even if tracked.
const SECRET_GLOBS: RegExp[] = [
  /^\.env(\..+)?$/i,
  /\.pem$/i,
  /\.key$/i,
  /\.p12$/i,
  /\.pfx$/i,
  /\.keystore$/i,
  /^id_(rsa|dsa|ecdsa|ed25519)$/i,
  /^secrets?\./i,
  /^credentials?$/i,
  /^\.npmrc$/i,
  /^\.netrc$/i,
];

const EXT_LANG: Record<string, string> = {
  ts: 'typescript', tsx: 'typescript', mts: 'typescript', cts: 'typescript',
  js: 'javascript', jsx: 'javascript', mjs: 'javascript', cjs: 'javascript',
  py: 'python', pyi: 'python', go: 'go', rs: 'rust', java: 'java', kt: 'kotlin',
  c: 'c', h: 'c', cc: 'cpp', cpp: 'cpp', hpp: 'cpp', cs: 'csharp', php: 'php',
  rb: 'ruby', swift: 'swift', scala: 'scala', dart: 'dart', lua: 'lua', sh: 'shell',
  sql: 'sql', css: 'css', scss: 'scss', html: 'html', vue: 'vue', svelte: 'svelte',
};

export function languageFromPath(path: string): string | null {
  const dot = path.lastIndexOf('.');
  if (dot < 0) return null;
  return EXT_LANG[path.slice(dot + 1).toLowerCase()] ?? null;
}

export function isSourceFile(path: string): boolean {
  return languageFromPath(path) != null;
}

export function isIgnoredPath(relPath: string): boolean {
  return relPath.split(/[/\\]/).some((seg) => IGNORE_DIRS.has(seg));
}

export function isSecretPath(path: string): boolean {
  const base = basename(path);
  return SECRET_GLOBS.some((re) => re.test(base));
}

const GENERATED_MARKERS = [/@generated\b/, /DO NOT EDIT/i, /Code generated by/i, /This file was automatically generated/i, /auto-generated/i];

export function isGenerated(path: string, content: string | undefined): boolean {
  if (/\.min\.(js|css)$/i.test(path) || /\.(d\.ts|pb\.go|generated\.[a-z]+)$/i.test(path)) return true;
  if (!content) return false;
  const head = content.slice(0, 2000);
  if (GENERATED_MARKERS.some((re) => re.test(head))) return true;
  // minified: a very long line with no newlines
  const firstNl = content.indexOf('\n');
  if ((firstNl < 0 ? content.length : firstNl) > 5000) return true;
  return false;
}

export interface CaptureDecision {
  ok: boolean;
  reason?: string;
}

/** Decide whether a file's edit should become a signal. relPath should be repo-relative. */
export function shouldCapture(relPath: string, content: string | undefined): CaptureDecision {
  if (!isSourceFile(relPath)) return { ok: false, reason: 'not a recognized source file' };
  if (isIgnoredPath(relPath)) return { ok: false, reason: 'ignored directory (deps/build)' };
  if (isSecretPath(relPath)) return { ok: false, reason: 'secret file' };
  if (content != null && content.length > MAX_FILE_SIZE) return { ok: false, reason: 'file too large (>1MB)' };
  if (isGenerated(relPath, content)) return { ok: false, reason: 'generated file' };
  return { ok: true };
}

const SECRET_PATTERNS: Array<[RegExp, string]> = [
  [/-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----/g, '[REDACTED_PRIVATE_KEY]'],
  [/AKIA[0-9A-Z]{16}/g, '[REDACTED_AWS_KEY]'],
  [/\bghp_[A-Za-z0-9]{20,}/g, '[REDACTED_GH_TOKEN]'],
  [/\bgithub_pat_[A-Za-z0-9_]{20,}/g, '[REDACTED_GH_TOKEN]'],
  [/\bxox[baprs]-[A-Za-z0-9-]{10,}/g, '[REDACTED_SLACK_TOKEN]'],
  [/\bAIza[0-9A-Za-z_-]{20,}/g, '[REDACTED_GOOGLE_KEY]'],
  [/\b(bearer\s+)[A-Za-z0-9._-]{16,}/gi, '$1[REDACTED]'],
  [/((?:api[_-]?key|secret|token|password|passwd|pwd|access[_-]?token|client[_-]?secret)\s*[:=]\s*['"]?)[^'"\s]{8,}(['"]?)/gi, '$1[REDACTED]$2'],
];

export function scrubSecrets(text: string): string {
  let out = text;
  for (const [re, repl] of SECRET_PATTERNS) out = out.replace(re, repl);
  return out;
}

export function capExcerpt(text: string): string {
  let lines = text.split('\n');
  let truncated = lines.length > MAX_EXCERPT_LINES;
  if (truncated) lines = lines.slice(0, MAX_EXCERPT_LINES);
  let out = lines.join('\n');
  if (out.length > MAX_EXCERPT_BYTES) {
    out = out.slice(0, MAX_EXCERPT_BYTES);
    truncated = true;
  }
  return truncated ? out + '\n…[truncated]' : out;
}

/** Scrub then cap — the transform applied to every stored excerpt. */
export function sanitizeExcerpt(text: string | null | undefined): string | null {
  if (text == null || text === '') return null;
  return capExcerpt(scrubSecrets(text));
}
